[package]
name = "assignment_7"
version = "0.1.0"
authors = ["maj"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shaheen = {path = "../shaheen"}
